### ISSUE TITLE
What training data should be passed to the module kanachan.training.iql ?

### ISSUE THREAD

**Issue by constellation39** [Cryolite/kanachan#19]
I apologize for opening such a simple question, i know few about the deep learning.
I realized I didn't have the data needed for kanachan.training.iql.
I looked at the implementation of IteratorAdaptor and i found that i had no way to combine such data with the existing data.
I checked another issues https://github.com/Cryolite/kanachan/issues/15 but i still don't understand how kanachan.training.iql should be used, or if it can be used?

Thank you for any answer

**Comment by constellation39** [comment]
I finished kanachan.training.ber

**Comment by Cryolite** [comment]
`kanachan.training.iql.train` is implemented in a usable state. However, there is no documentation of the training data format for this program. I'm now working on the documentation, and implementation of a program to convert the output of cryolite/kanachan.annotate to the format.

**Comment by Cryolite** [comment]
Documentation is almost complete.
https://github.com/Cryolite/kanachan/wiki/Notes-on-Training-Data#training-data-format-for-offline-reinforcement-learning

I'm still working on implementation of the program converting annotations.

**Comment by constellation39** [comment]
I get it.
thank you for your hard work.
