### ISSUE TITLE
Is the mjai-app module in the source code available now?

### ISSUE THREAD

**Issue by constellation39** [Cryolite/kanachan#20]
I'm trying to use this module, but encountering errors.

**Comment by Cryolite** [comment]
The implementation under the `mjai.app` directory are still under active development. Especially, there is a high possibility that the specification of model files will be changed. Please wait for a while.

**Comment by constellation39** [comment]
thanks, i wait.

**Comment by shinkuan** [comment]
Any update? mjai.app just got re-launched.

**Comment by shinkuan** [comment]
I made a implement for mjai-app, you might want to see it.
https://github.com/Cryolite/kanachan/discussions/50

**Comment by Cryolite** [comment]
I have officially started supporting [AIJansou (mjai.app)](https://mjai.app/) in the `develop` branch. For detailed instructions on how to convert a model into a `.zip` file for submission, please refer to https://github.com/Cryolite/kanachan/tree/develop/mjai.app/README.md .
