### ISSUE TITLE
annotation went error

### ISSUE THREAD

**Issue by WuSheng125** [Cryolite/kanachan#60]
```sh
`std::terminate' is called after throwing an instance of `boost::exception_detail::error_info_injector<std::invalid_argument>'.
/opt/kanachan/src/annotation/player_state.cpp:232: Kanachan::PlayerState::PlayerState(uint_fast8_t, uint_fast32_t, uint_fast32_t, uint_fast8_t, int_fast32_t, int_fast32_t): level = 10701
Backtrace:
 0# Kanachan::PlayerState::PlayerState(unsigned char, unsigned long, unsigned long, unsigned char, long, long) in build/src/annotation/annotate
 1# (anonymous namespace)::convert(std::filesystem::__cxx11::path const&) in build/src/annotation/annotate
 2# main in build/src/annotation/annotate
 3# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 4# _start in build/src/annotation/annotate
```
When I use annotation to convert data, I got this error. I have not changed any code. Did I make something wrong?
This is the data file I used:
[230101-ccb3b090-40ef-4f3f-9377-63472b840f16.zip](https://github.com/Cryolite/kanachan/files/13536256/230101-ccb3b090-40ef-4f3f-9377-63472b840f16.zip)

**Comment by shinkuan** [comment]
The data worked fine for me. It might be problem with your docker image.

Annotation result of the file you gave: [out.txt](https://github.com/Cryolite/kanachan/files/13536649/out.txt)

**Comment by WuSheng125** [comment]
Thank you for your help!
Now I get the proper output by using your docker image.
